apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-ventas
  labels:
    app: back-ventas
spec:
  replicas: 2
  selector:
    matchLabels:
      app: back-ventas
  template:
    metadata:
      labels:
        app: back-ventas
    spec:
      containers:
        - name: back-ventas
          image: 633079526033.dkr.ecr.us-east-1.amazonaws.com/ventas-api:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: db-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: back-ventas-svc
spec:
  selector:
    app: back-ventas
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30081